"""antcrew-proxy — LLM key proxy for antcrew-platform.

Receives requests from the platform, validates the proxy token, strips it,
and forwards the request to api.anthropic.com with the real ANTHROPIC_API_KEY.
The platform never holds the customer's Anthropic key; the customer never
gives their key to the platform.

Environment variables (required):
  ANTHROPIC_API_KEY  — your real Anthropic API key (sk-ant-...)
  PROXY_TOKEN        — UUID token generated by the platform (kept secret from platform)

Optional:
  ANTHROPIC_BASE_URL — override upstream endpoint (default: https://api.anthropic.com)
  HOST               — bind host (default: 0.0.0.0)
  PORT               — bind port (default: 8080)
"""
from __future__ import annotations

import hmac
import os

import httpx
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import StreamingResponse
from starlette.background import BackgroundTask

ANTHROPIC_API_KEY: str = os.environ["ANTHROPIC_API_KEY"]
PROXY_TOKEN: str = os.environ["PROXY_TOKEN"]
ANTHROPIC_BASE: str = os.environ.get("ANTHROPIC_BASE_URL", "https://api.anthropic.com").rstrip("/")

_client = httpx.AsyncClient(timeout=httpx.Timeout(600.0))

app = FastAPI(title="antcrew-proxy", docs_url=None, redoc_url=None, openapi_url=None)


def _verify(request: Request) -> None:
    """Reject requests that don't carry the configured proxy token."""
    token = request.headers.get("x-api-key", "")
    if not hmac.compare_digest(token.encode(), PROXY_TOKEN.encode()):
        raise HTTPException(401, "Invalid proxy token")


@app.get("/health")
async def health() -> dict:
    return {"ok": True}


@app.api_route("/{path:path}", methods=["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD"])
async def proxy(path: str, request: Request) -> StreamingResponse:
    """Proxy all requests to Anthropic, substituting the real API key."""
    _verify(request)

    headers = {
        k: v
        for k, v in request.headers.items()
        if k.lower() not in ("host", "x-api-key", "content-length", "transfer-encoding")
    }
    headers["x-api-key"] = ANTHROPIC_API_KEY

    upstream_req = _client.build_request(
        method=request.method,
        url=f"{ANTHROPIC_BASE}/{path}",
        headers=headers,
        content=await request.body(),
        params=dict(request.query_params),
    )
    resp = await _client.send(upstream_req, stream=True)

    # Pass through all headers except hop-by-hop ones that would confuse clients.
    forward_headers = {
        k: v
        for k, v in resp.headers.items()
        if k.lower() not in ("content-encoding", "transfer-encoding", "content-length")
    }

    return StreamingResponse(
        resp.aiter_raw(),
        status_code=resp.status_code,
        headers=forward_headers,
        media_type=resp.headers.get("content-type"),
        background=BackgroundTask(resp.aclose),
    )


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host=os.environ.get("HOST", "0.0.0.0"), port=int(os.environ.get("PORT", "8080")))
