"""antcrew-proxy — multi-provider LLM key proxy for antcrew-platform.

Receives requests from the platform, validates the proxy token, and forwards
to the correct upstream LLM provider using the real API key. The platform
never holds any provider key — only the UUID token used to authenticate here.

Request routing by path prefix:
  POST /anthropic/v1/messages              → api.anthropic.com
  POST /openai/v1/chat/completions         → api.openai.com
  POST /groq/openai/v1/chat/completions    → api.groq.com/openai
  POST /gemini/v1/chat/completions         → generativelanguage.googleapis.com/v1beta/openai
  POST /moonshot/v1/chat/completions       → api.moonshot.cn/v1

Required environment variables:
  PROXY_TOKEN   — token generated by the platform (keep secret)

Provider keys (configure only the ones you use):
  ANTHROPIC_API_KEY  — sk-ant-…
  OPENAI_API_KEY     — sk-proj-…
  GROQ_API_KEY       — gsk_…
  GEMINI_API_KEY     — AIza…
  MOONSHOT_API_KEY   — sk-…  (Moonshot AI / Kimi)

Optional overrides:
  ANTHROPIC_BASE_URL / OPENAI_BASE_URL / GROQ_BASE_URL / GEMINI_BASE_URL / MOONSHOT_BASE_URL
"""
from __future__ import annotations

import hmac
import logging
import os

import httpx
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import StreamingResponse
from starlette.background import BackgroundTask

log = logging.getLogger(__name__)

PROXY_TOKEN: str = os.environ["PROXY_TOKEN"]

_UPSTREAM: dict[str, str] = {
    "anthropic": os.environ.get("ANTHROPIC_BASE_URL", "https://api.anthropic.com").rstrip("/"),
    "openai":    os.environ.get("OPENAI_BASE_URL",    "https://api.openai.com").rstrip("/"),
    "groq":      os.environ.get("GROQ_BASE_URL",      "https://api.groq.com/openai").rstrip("/"),
    "gemini":    os.environ.get("GEMINI_BASE_URL",    "https://generativelanguage.googleapis.com/v1beta/openai").rstrip("/"),
    "moonshot":  os.environ.get("MOONSHOT_BASE_URL",  "https://api.moonshot.cn/v1").rstrip("/"),
}

_KEYS: dict[str, str] = {
    p: v
    for p, v in {
        "anthropic": os.environ.get("ANTHROPIC_API_KEY", ""),
        "openai":    os.environ.get("OPENAI_API_KEY",    ""),
        "groq":      os.environ.get("GROQ_API_KEY",      ""),
        "gemini":    os.environ.get("GEMINI_API_KEY",    ""),
        "moonshot":  os.environ.get("MOONSHOT_API_KEY",  ""),
    }.items()
    if v
}

# Anthropic uses x-api-key; OpenAI-compatible providers use Authorization: Bearer
_OPENAI_COMPAT = frozenset({"openai", "groq", "gemini", "moonshot"})
_HOP_BY_HOP = frozenset({"host", "x-api-key", "authorization", "content-length", "transfer-encoding"})

_client = httpx.AsyncClient(timeout=httpx.Timeout(600.0))

app = FastAPI(title="antcrew-proxy", docs_url=None, redoc_url=None, openapi_url=None)


@app.on_event("startup")
async def _startup() -> None:
    active = list(_KEYS)
    if not active:
        log.warning("antcrew-proxy: no provider keys configured — all requests will return 503")
    else:
        log.info("antcrew-proxy: active providers: %s", ", ".join(active))


def _verify(request: Request) -> None:
    """Accept token from x-api-key (Anthropic SDK) or Authorization: Bearer (OpenAI SDK)."""
    token = request.headers.get("x-api-key", "")
    if not token:
        auth = request.headers.get("authorization", "")
        if auth.lower().startswith("bearer "):
            token = auth[7:].strip()
    if not hmac.compare_digest(token.encode(), PROXY_TOKEN.encode()):
        raise HTTPException(401, "Invalid proxy token")


@app.get("/health")
async def health() -> dict:
    """Health check — also reports which providers are configured."""
    return {"ok": True, "providers": list(_KEYS)}


@app.api_route("/{provider}/{path:path}", methods=["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD"])
async def proxy(provider: str, path: str, request: Request) -> StreamingResponse:
    """Forward a request to the upstream LLM provider after token validation."""
    _verify(request)

    upstream_base = _UPSTREAM.get(provider)
    if upstream_base is None:
        raise HTTPException(404, f"Unknown provider '{provider}'. Supported: {', '.join(_UPSTREAM)}")

    api_key = _KEYS.get(provider)
    if not api_key:
        raise HTTPException(
            503,
            f"No API key configured for provider '{provider}'. "
            f"Set {provider.upper()}_API_KEY on the proxy and restart.",
        )

    # Strip inbound auth headers and inject the real provider key
    headers = {k: v for k, v in request.headers.items() if k.lower() not in _HOP_BY_HOP}
    if provider in _OPENAI_COMPAT:
        headers["Authorization"] = f"Bearer {api_key}"
    else:
        headers["x-api-key"] = api_key

    req = _client.build_request(
        method=request.method,
        url=f"{upstream_base}/{path}",
        headers=headers,
        content=await request.body(),
        params=dict(request.query_params),
    )
    resp = await _client.send(req, stream=True)

    forward_headers = {
        k: v
        for k, v in resp.headers.items()
        if k.lower() not in ("content-encoding", "transfer-encoding", "content-length")
    }
    return StreamingResponse(
        resp.aiter_raw(),
        status_code=resp.status_code,
        headers=forward_headers,
        media_type=resp.headers.get("content-type"),
        background=BackgroundTask(resp.aclose),
    )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host=os.environ.get("HOST", "0.0.0.0"), port=int(os.environ.get("PORT", "8080")))
